name: autoequal_gen
description: |
  Codegenerator which can simplify work with 'equatable'.
  It will generate 'List<Object> props' priviate extensions for all annotated classes.
version: 0.2.0
homepage: https://github.com/sunnydaydev/autoequal

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.1.0
  build: ^1.6.3
  source_gen: ^0.9.10+3
  autoequal: ^0.2.0
  equatable: ^2.0.0

dev_dependencies:
  build_test: ^1.3.7
  build_runner: ^1.11.5
  test: ^1.16.5
  pedantic: ^1.11.0
