name: example
description: Autoequal example
version: 1.0.0

publish_to: "none"

environment:
  sdk: ^3.0.0

dependencies:
  autoequal:
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.4.7
  autoequal_gen:
  lints: ">=3.0.0 <6.0.0"
  test: ^1.24.9
  derry: ^1.5.0
  generator_test: ^0.3.1

scripts: scripts.yaml
